### ISSUE TITLE
Use automatic sidecar integration

### ISSUE THREAD

**Issue by aym-frikha** [juju-solutions/bundle-istio#6]
Feature request to allow automatic sidecar integration for the jupyterhub notebook pods for example. 
Example:
A data scientists that has access to a notebook need to download data from an external storage solution. This solution has a special authentication mechanism like Kerberos that manage access to data. A sidecar container to the notebook pod can be a good solution to do automatic Kerberos authentication and provide the user with a token that allows him to download his data. 

This is a simple use case but it can be expanded to multiple other use cases.
We can use Istio to provide this mechanism or any other automatic sidecar integration mechanism.

**Comment by knkski** [comment]
Example of desired additional YAML injected into sidecar:

```yaml
 - name: "[[ $index ]]"
      [[ toYaml $value | indent 4 ]]
      [[ end ]]
      [[- end ]]
# Additional YAML
  - name: kerberos-sidecar
    image: kerberos-image:latest
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
# End additional YAML
  volumes:
  [[- if (isset .ObjectMeta.Annotations `sidecar.istio.io/bootstrapOverride`) ]]
  - name: custom-bootstrap-volume
    configMap:
```
